[build-system]
requires = ["setuptools", "cython>=3.0.0", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "fish2pano"
requires-python = ">=3.7"
version = "0.2.0"
readme = "README.md"
dependencies = [
    "numpy"
]

